-- | The image object
module OpenAI.Servant.V1.Images.Image
    ( -- * Types
      Image(..)
    ) where

import OpenAI.Servant.Prelude

-- | Represents the url or the content of an image generated by the OpenAI API
data Image = Image
    { b64_json :: Maybe Text
    , url :: Maybe Text
    , revised_prompt :: Maybe Text
    } deriving stock (Generic, Show)
      deriving anyclass (FromJSON)
